import type { CategoryId, Product } from '@duhahe/shared';
import type { IconName } from '../components/Icon';

/**
 * Product placeholder art.
 *
 * Every product gets its own food/kitchen icon (blue gradient + white icon),
 * so each tile reads as the actual item. The icon is chosen from an exact
 * per-product map, falling back to a per-emoji map, then per-category.
 */
export interface ProductArt {
  icon: IconName;
  c1: string;
  c2: string;
}

const BLUE_C1 = '#9fdcf0';
const BLUE_C2 = '#00a9d6';

export const categoryArt: Record<CategoryId, ProductArt> = {
  staples: { icon: 'grain', c1: BLUE_C1, c2: BLUE_C2 },
  vegetables: { icon: 'leaf', c1: BLUE_C1, c2: BLUE_C2 },
  fruits: { icon: 'fruit-citrus', c1: BLUE_C1, c2: BLUE_C2 },
  kitchenware: { icon: 'silverware-fork-knife', c1: BLUE_C1, c2: BLUE_C2 },
  household: { icon: 'broom', c1: BLUE_C1, c2: BLUE_C2 },
  drinks: { icon: 'cup', c1: BLUE_C1, c2: BLUE_C2 },
  personal_care: { icon: 'hand-wash', c1: BLUE_C1, c2: BLUE_C2 },
  other: { icon: 'candle', c1: BLUE_C1, c2: BLUE_C2 },
};

/** Exact icon per product so each food shows its own icon. */
const productById: Record<string, IconName> = {
  // Staples
  s001: 'rice',
  s002: 'rice',
  s004: 'corn',
  s005: 'corn',
  s008: 'grain',
  s010: 'bowl-mix',
  s012: 'seed',
  s013: 'seed',
  s014: 'seed',
  s016: 'seed',
  s018: 'seed',
  s019: 'seed',
  s021: 'peanut-outline',
  s024: 'sack',
  s025: 'pot-steam',
  s026: 'pot-steam',
  s030: 'candy',
  s031: 'oil',
  s032: 'shaker-outline',
  s033: 'tea',
  s034: 'coffee',
  s036: 'egg-outline',
  s037: 'cheese',
  s040: 'shaker-outline',
  s043: 'chili-mild',
  s044: 'pasta',
  s045: 'pasta',
  s047: 'cookie',
  s051: 'candy',
  s052: 'oil',
  s053: 'cup',
  s054: 'cup',
  s055: 'cup',
  s056: 'cheese',
  s057: 'cheese',
  s058: 'turkey',
  s059: 'food-steak',
  s060: 'food-steak',
  s061: 'food-drumstick',
  s062: 'fish',
  s063: 'fish',
  s064: 'fish',
  s065: 'bread-slice',
  s066: 'grain',
  s067: 'bee',
  s068: 'cookie',
  s069: 'peanut-outline',
  s070: 'seed',
  s071: 'shaker-outline',

  // Vegetables
  v001: 'food-apple',
  v002: 'circle-slice-8',
  v003: 'circle-slice-8',
  v004: 'leaf',
  v006: 'sprout',
  v007: 'sprout',
  v009: 'carrot',
  v010: 'seed',
  v011: 'seed',
  v012: 'chili-mild',
  v013: 'chili-mild',
  v015: 'circle',
  v016: 'leaf',
  v017: 'pumpkin',
  v018: 'leaf',
  v020: 'carrot',
  v021: 'circle',
  v022: 'leaf',
  v023: 'leaf',
  v024: 'leaf',
  v025: 'circle-slice-8',
  v027: 'sprout',
  v028: 'sprout',
  v031: 'leaf',
  v032: 'leaf',
  v033: 'leaf',
  v034: 'leaf',
  v035: 'corn',
  v036: 'leaf',
  v037: 'chili-mild',

  // Fruits
  f001: 'fruit-pear',
  f002: 'fruit-citrus',
  f003: 'fruit-citrus',
  f004: 'fruit-citrus',
  f005: 'fruit-citrus',
  f006: 'fruit-citrus',
  f007: 'fruit-watermelon',
  f008: 'fruit-citrus',
  f009: 'fruit-citrus',
  f010: 'fruit-pear',
  f011: 'fruit-pineapple',
  f012: 'fruit-citrus',
  f013: 'food-apple',
  f014: 'fruit-grapes',
  f015: 'food-apple',
  f016: 'fruit-cherries',
  f017: 'fruit-cherries',
  f018: 'fruit-cherries',
  f019: 'fruit-citrus',
  f020: 'fruit-pear',
  f021: 'food-apple',
  f024: 'circle',
  f026: 'fruit-watermelon',
  f028: 'circle',
  f031: 'fruit-pear',
  f032: 'fruit-citrus',
  f033: 'fruit-pineapple',
  f034: 'fruit-citrus',
  f035: 'fruit-cherries',
  f036: 'fruit-cherries',

  // Kitchenware
  k001: 'pot',
  k002: 'pan',
  k003: 'silverware-clean',
  k004: 'knife',
  k005: 'cube-outline',
  k006: 'bowl-mix',
  k007: 'bucket',
  k008: 'cup-outline',
  k009: 'bottle-tonic',
  k010: 'stove',
  k011: 'water',
  k012: 'package-variant-closed',
  k013: 'fire',
  k014: 'silverware-fork-knife',
  k015: 'bowl-mix',
  k016: 'basket',
  k017: 'water',
  k018: 'cup-outline',
};

/** Fallback icon per emoji for any product not in the exact map. */
const art: Record<string, IconName> = {
  '🍚': 'rice',
  '🌾': 'grain',
  '🍞': 'bread-slice',
  '🥣': 'bowl-mix',
  '🫘': 'seed',
  '🟢': 'seed',
  '🥜': 'peanut-outline',
  '🥔': 'sack',
  '🍠': 'pot-steam',
  '🍬': 'candy',
  '🛢️': 'barrel',
  '🧂': 'shaker-outline',
  '🍵': 'tea',
  '☕': 'coffee',
  '🥚': 'egg-outline',
  '🧈': 'cheese',
  '🫙': 'bottle-tonic',
  '🌶️': 'chili-mild',
  '🍝': 'pasta',
  '🍪': 'cookie',
  '🥛': 'cup',
  '🧀': 'cheese',
  '🐔': 'turkey',
  '🥩': 'food-steak',
  '🐖': 'food-drumstick',
  '🐟': 'fish',
  '🍯': 'bee',
  '🍫': 'cookie',
  '🍅': 'food-apple',
  '🧅': 'circle-slice-8',
  '🥬': 'leaf',
  '🥕': 'carrot',
  '🫛': 'seed',
  '🫑': 'chili-mild',
  '🍆': 'circle',
  '🥒': 'leaf',
  '🎃': 'pumpkin',
  '🟣': 'carrot',
  '🔴': 'circle',
  '🌿': 'leaf',
  '🧄': 'circle-slice-8',
  '🥦': 'sprout',
  '🌽': 'corn',
  '🥑': 'fruit-pear',
  '🍌': 'fruit-citrus',
  '🍊': 'fruit-citrus',
  '🍋': 'fruit-citrus',
  '🍉': 'fruit-watermelon',
  '🟠': 'fruit-citrus',
  '🥭': 'fruit-citrus',
  '🍍': 'fruit-pineapple',
  '🍎': 'food-apple',
  '🍇': 'fruit-grapes',
  '🍓': 'fruit-cherries',
  '🫐': 'fruit-cherries',
  '🍑': 'fruit-citrus',
  '🥝': 'circle',
  '🟡': 'fruit-citrus',
  '🥥': 'circle',
  '🟩': 'fruit-citrus',
  '🍈': 'fruit-watermelon',
  '🍐': 'fruit-pear',
  '🍲': 'pot',
  '🍳': 'pan',
  '🥄': 'silverware-clean',
  '🔪': 'knife',
  '🪵': 'cube-outline',
  '🪣': 'bucket',
  '🥤': 'cup-outline',
  '🧴': 'bottle-tonic',
  '🔥': 'fire',
  '💧': 'water',
  '📦': 'package-variant-closed',
  '🕯️': 'candle',
  '🧺': 'basket',
  '🪨': 'circle',
};

export function productArt(product: Product): ProductArt {
  const icon = productById[product.id] ?? art[product.emoji] ?? categoryArt[product.category].icon;
  return { icon, c1: BLUE_C1, c2: BLUE_C2 };
}